apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-web-api-deployment
  namespace: application
spec:
  replicas: 1
  selector:
     matchLabels:
       app: cars-web-api
  template:
    metadata:
      labels:
        app: cars-web-api
    spec:
      containers:
      - name: cars-web-api
        image: sebtec1212/carswebapi:0.1-postgres
        imagePullPolicy: IfNotPresent
        env:
          - name: "CONNECTION_STRING"
            valueFrom:
              secretKeyRef:
                name: cars-connection-string-secret
                key: CONNECTION_STRING
        ports:
        - containerPort: 80
      initContainers:
      - name: cars-init
        image: sebtec1212/carswebapi:0.2-init
        imagePullPolicy: IfNotPresent
        env:
        - name: "CONNECTION_STRING"
          valueFrom:
            secretKeyRef:
              name: cars-connection-string-secret
              key: CONNECTION_STRING