apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-car-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-car
  template:
    metadata:
      labels:
        app: react-car
    spec:
      containers:
        - name: react-car-client
          image: yanamanhusheva/car-react-app:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
