apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: application
  name: postgres-cars-volume-claim
  labels:
    app: postgres-cars
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi