apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard.backend" . | nindent 4 }}
type: Opaque
data:
  CONNECTION_STRING: {{ include "common.connection.string" (dict "databaseRoot" .Values.postgres ) | b64enc }}
