apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard.backend" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
  selector: {{- include "common.labels.matchLabels.backend" . | nindent 4 }}