apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cars-destination
spec:
  host: local-cars-backend
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5 
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80
