postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "admin"
        username: "admin"
        password: "admin"
        database: "microservices"
  fullnameOverride: "postgres"
  primary:
    persistence:
      mountPath: /var/lib/postgresql/data
      size: 2Gi
  readReplicas:
    persistence:
      enabled: false

kafka:
  fullnameOverride: kafka
  numPartitions: 3
  autoCreateTopicsEnable: false
  provisioning:
    enabled: true
    topics:
     - name: cars
     - name: hotels