apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard.backend" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels.backend" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.standard.backend" . | nindent 8 }}
    spec:
      containers:
        - name: consumer
          image: {{ include "backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | quote }}
          ports:
            - containerPort: 80