apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres